% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{float}
\floatplacement{figure}{H}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={AI Memory and Switching Costs: Pilot Survey Results},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{AI Memory and Switching Costs: Pilot Survey Results}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Descriptive Analysis of Prolific Sample}
\author{}
\date{\vspace{-2.5em}April 03, 2026}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\begin{verbatim}
## N after cleaning: 206 
## Cleaned data saved. Rows: 206  Cols: 118
\end{verbatim}

\begin{verbatim}
## 
## === Demand Suppression (Q13 - Q14) ===
## Mean = $1.21, SD = $6.70, p = 0.0108
## 
## === Portability Recovery (Q15 - Q14) ===
## Mean = $2.46, SD = $6.85, p = 0.0000
## 
## === Effective Portability (phi_eff) ===
## Median = 1.00, Mean = 1.02, N = 50
## 
## === Consistency Check ===
## W2 >= W3 >= W4: 74.3%
## W2 >= W4: 96.0%
## 
## Sensitivity analysis saved.
\end{verbatim}

\begin{verbatim}
## === Regression: Demand Suppression on Usage Frequency ===
## 
## Call:
## lm(formula = demand_suppression ~ freq_num + age_group + gender + 
##     education, data = df_reg)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -47.218  -1.822  -0.663   1.771  36.716 
## 
## Coefficients:
##                                          Estimate Std. Error t value Pr(>|t|)
## (Intercept)                                3.0928     2.3510   1.315   0.1899
## freq_num                                   0.5015     0.4485   1.118   0.2649
## age_group25-34                            -2.8802     1.8670  -1.543   0.1246
## age_group35-44                            -2.8091     1.8319  -1.533   0.1268
## age_group45-54                            -5.0729     1.9361  -2.620   0.0095
## age_group55-64                            -2.4036     2.2753  -1.056   0.2921
## age_group65+                              -3.7004     2.5100  -1.474   0.1421
## genderNon-binary                          -2.4695     5.3040  -0.466   0.6420
## genderWoman                               -0.4675     0.9813  -0.476   0.6343
## educationDoctoral or professional degree   2.7389     4.2932   0.638   0.5243
## educationHigh school or less              -3.1110     1.4833  -2.097   0.0373
## educationMaster's degree                  -0.1216     1.5195  -0.080   0.9363
## educationSome college                      1.0660     1.1541   0.924   0.3569
##                                            
## (Intercept)                                
## freq_num                                   
## age_group25-34                             
## age_group35-44                             
## age_group45-54                           **
## age_group55-64                             
## age_group65+                               
## genderNon-binary                           
## genderWoman                                
## educationDoctoral or professional degree   
## educationHigh school or less             * 
## educationMaster's degree                   
## educationSome college                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 6.616 on 189 degrees of freedom
## Multiple R-squared:  0.08359,    Adjusted R-squared:  0.0254 
## F-statistic: 1.437 on 12 and 189 DF,  p-value: 0.1523
\end{verbatim}

\newpage

\section{Introduction}\label{introduction}

This report summarizes the pilot survey for a study on AI memory and
platform lock-in. The survey elicits beliefs about AI memory,
willingness to accept (WTA) compensation for memory erasure, and
willingness to pay (WTP) for a competing AI assistant under varying data
portability scenarios. These measures map directly onto a theoretical
model of switching costs driven by accumulated personalization data.

The pilot was fielded on Prolific with N = 206 respondents who completed
the survey in a median of 5.2 minutes. All WTP/WTA questions were asked
within-subjects (the full experiment will use a between-subjects
design).

\section{Sample Description}\label{sample-description}

\subsection{Demographics}\label{demographics}

\begin{longtable}[t]{llrr}
\caption{\label{tab:tab-demographics}Sample Demographics}\\
\toprule
Variable & Category & N & \%\\
\midrule
\cellcolor{gray!10}{age\_group} & \cellcolor{gray!10}{18-24} & \cellcolor{gray!10}{18} & \cellcolor{gray!10}{8.7}\\
\cmidrule{1-4}\pagebreak[0]
age\_group & 25-34 & 51 & 24.8\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{age\_group} & \cellcolor{gray!10}{35-44} & \cellcolor{gray!10}{69} & \cellcolor{gray!10}{33.5}\\
\cmidrule{1-4}\pagebreak[0]
age\_group & 45-54 & 39 & 18.9\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{age\_group} & \cellcolor{gray!10}{55-64} & \cellcolor{gray!10}{17} & \cellcolor{gray!10}{8.3}\\
\cmidrule{1-4}\pagebreak[0]
age\_group & 65+ & 12 & 5.8\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{gender} & \cellcolor{gray!10}{Man} & \cellcolor{gray!10}{109} & \cellcolor{gray!10}{52.9}\\
\cmidrule{1-4}\pagebreak[0]
gender & Non-binary & 2 & 1.0\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{gender} & \cellcolor{gray!10}{Woman} & \cellcolor{gray!10}{95} & \cellcolor{gray!10}{46.1}\\
\cmidrule{1-4}\pagebreak[0]
education & Bachelor's degree & 96 & 46.6\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{education} & \cellcolor{gray!10}{Doctoral or professional degree} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{1.5}\\
\cmidrule{1-4}\pagebreak[0]
education & High school or less & 27 & 13.1\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{education} & \cellcolor{gray!10}{Master's degree} & \cellcolor{gray!10}{26} & \cellcolor{gray!10}{12.6}\\
\cmidrule{1-4}\pagebreak[0]
education & Some college & 54 & 26.2\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{occupation} & \cellcolor{gray!10}{Creative \& Design} & \cellcolor{gray!10}{12} & \cellcolor{gray!10}{5.8}\\
\cmidrule{1-4}\pagebreak[0]
occupation & Education & 11 & 5.3\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{occupation} & \cellcolor{gray!10}{Finance} & \cellcolor{gray!10}{13} & \cellcolor{gray!10}{6.3}\\
\cmidrule{1-4}\pagebreak[0]
occupation & Healthcare & 14 & 6.8\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{occupation} & \cellcolor{gray!10}{Management \& Executive} & \cellcolor{gray!10}{18} & \cellcolor{gray!10}{8.7}\\
\cmidrule{1-4}\pagebreak[0]
occupation & Marketing \& Sales & 16 & 7.8\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{occupation} & \cellcolor{gray!10}{Other (please specify)} & \cellcolor{gray!10}{61} & \cellcolor{gray!10}{29.6}\\
\cmidrule{1-4}\pagebreak[0]
occupation & Research \& Academic & 10 & 4.9\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{occupation} & \cellcolor{gray!10}{Software \& IT} & \cellcolor{gray!10}{43} & \cellcolor{gray!10}{20.9}\\
\cmidrule{1-4}\pagebreak[0]
occupation & Student & 8 & 3.9\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{industry} & \cellcolor{gray!10}{Education} & \cellcolor{gray!10}{16} & \cellcolor{gray!10}{7.8}\\
\cmidrule{1-4}\pagebreak[0]
industry & Finance \& Insurance & 19 & 9.2\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{industry} & \cellcolor{gray!10}{Government} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{1.5}\\
\cmidrule{1-4}\pagebreak[0]
industry & Healthcare & 17 & 8.3\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{industry} & \cellcolor{gray!10}{Manufacturing} & \cellcolor{gray!10}{10} & \cellcolor{gray!10}{4.9}\\
\cmidrule{1-4}\pagebreak[0]
industry & Media \& Entertainment & 13 & 6.3\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{industry} & \cellcolor{gray!10}{Other (please specify)} & \cellcolor{gray!10}{56} & \cellcolor{gray!10}{27.2}\\
\cmidrule{1-4}\pagebreak[0]
industry & Retail \& E-commerce & 22 & 10.7\\
\cmidrule{1-4}\pagebreak[0]
\cellcolor{gray!10}{industry} & \cellcolor{gray!10}{Technology} & \cellcolor{gray!10}{50} & \cellcolor{gray!10}{24.3}\\
\bottomrule
\end{longtable}

\subsection{AI Platform Usage}\label{ai-platform-usage}

\begin{longtable}[t]{lrrrrrr}
\caption{\label{tab:tab-platform}Platform usage: personal, work, and paid subscriptions}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Personal Use} & \multicolumn{2}{c}{Work Use} & \multicolumn{2}{c}{Paid} \\
\cmidrule(l{3pt}r{3pt}){2-3} \cmidrule(l{3pt}r{3pt}){4-5} \cmidrule(l{3pt}r{3pt}){6-7}
Platform & N & \% & N & \% & N & \%\\
\midrule
\cellcolor{gray!10}{ChatGPT (OpenAI)} & \cellcolor{gray!10}{159} & \cellcolor{gray!10}{77.2} & \cellcolor{gray!10}{101} & \cellcolor{gray!10}{49.0} & \cellcolor{gray!10}{39} & \cellcolor{gray!10}{18.9}\\
Google Gemini & 120 & 58.3 & 52 & 25.2 & 8 & 3.9\\
\cellcolor{gray!10}{Microsoft Copilot} & \cellcolor{gray!10}{57} & \cellcolor{gray!10}{27.7} & \cellcolor{gray!10}{45} & \cellcolor{gray!10}{21.8} & \cellcolor{gray!10}{5} & \cellcolor{gray!10}{2.4}\\
Claude (Anthropic) & 41 & 19.9 & 25 & 12.1 & 8 & 3.9\\
\cellcolor{gray!10}{Grok (xAI)} & \cellcolor{gray!10}{28} & \cellcolor{gray!10}{13.6} & \cellcolor{gray!10}{8} & \cellcolor{gray!10}{3.9} & \cellcolor{gray!10}{5} & \cellcolor{gray!10}{2.4}\\
\addlinespace
Meta AI (Facebook / Instagram / WhatsApp) & 22 & 10.7 & 3 & 1.5 & 0 & 0.0\\
\cellcolor{gray!10}{Perplexity} & \cellcolor{gray!10}{14} & \cellcolor{gray!10}{6.8} & \cellcolor{gray!10}{6} & \cellcolor{gray!10}{2.9} & \cellcolor{gray!10}{4} & \cellcolor{gray!10}{1.9}\\
DeepSeek & 6 & 2.9 & 1 & 0.5 & 0 & 0.0\\
\cellcolor{gray!10}{Character.AI} & \cellcolor{gray!10}{6} & \cellcolor{gray!10}{2.9} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.0} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.0}\\
\bottomrule
\end{longtable}

ChatGPT dominates personal use (77\%) and work use. 28\% of respondents
pay for any AI subscription. The mean respondent uses 2.3 platforms, and
65\% qualify as multihomers (2+ platforms).

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-platforms-1} 

}

\caption{AI Platform Usage (Personal vs. Work)}\label{fig:fig-platforms}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-frequency-1} 

}

\caption{Usage Frequency}\label{fig:fig-frequency}
\end{figure}

Regarding multihoming frequency (Q4): Always (1\%), Never (24\%), Often
(12\%), Rarely (28\%), Sometimes (35\%).

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-multihoming-1} 

}

\caption{Number of AI Platforms Used}\label{fig:fig-multihoming}
\end{figure}

\subsection{Ad-Free Valuation}\label{ad-free-valuation}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-adfree-1} 

}

\caption{WTP for Ad-Free AI}\label{fig:fig-adfree}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-adsentiment-1} 

}

\caption{Ad Sentiment}\label{fig:fig-adsentiment}
\end{figure}

Mean ad sentiment is 2.1 on a 1--7 scale (1 = strongly dislike). The
majority (62\%) would rather see ads than pay, despite strongly
disliking ads.

\section{Memory Beliefs and Switching
Perceptions}\label{memory-beliefs-and-switching-perceptions}

\subsection{Memory Awareness}\label{memory-awareness}

\begin{longtable}[t]{llrr}
\caption{\label{tab:tab-memory}Memory Awareness Crosstab}\\
\toprule
AI Remembers? & Reviewed Memories? & N & \%\\
\midrule
\cellcolor{gray!10}{I'm not sure} & \cellcolor{gray!10}{I didn't know I could} & \cellcolor{gray!10}{8} & \cellcolor{gray!10}{3.9}\\
I'm not sure & No & 26 & 12.6\\
\cellcolor{gray!10}{I'm not sure} & \cellcolor{gray!10}{Yes} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{1.5}\\
No & I didn't know I could & 6 & 2.9\\
\cellcolor{gray!10}{No} & \cellcolor{gray!10}{No} & \cellcolor{gray!10}{10} & \cellcolor{gray!10}{4.9}\\
\addlinespace
No & Yes & 9 & 4.4\\
\cellcolor{gray!10}{Yes} & \cellcolor{gray!10}{I didn't know I could} & \cellcolor{gray!10}{16} & \cellcolor{gray!10}{7.8}\\
Yes & No & 67 & 32.5\\
\cellcolor{gray!10}{Yes} & \cellcolor{gray!10}{Yes} & \cellcolor{gray!10}{61} & \cellcolor{gray!10}{29.6}\\
\bottomrule
\end{longtable}

70\% of respondents believe their AI remembers them. Only 35\% have
reviewed their AI's memories, and 15\% did not know they could.

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-memory-1} 

}

\caption{Memory Beliefs Overview}\label{fig:fig-memory}
\end{figure}

Perceived improvement from memory averages 4.6 / 7 (SD = 1.6),
indicating moderate perceived value.

\subsection{Switching Losses}\label{switching-losses}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-losses-1} 

}

\caption{Perceived Switching Losses}\label{fig:fig-losses}
\end{figure}

30\% report ``nothing significant'' would be lost from switching. The
most common concern is losing preferences/style, followed by
conversation history.

\subsection{Time to Re-Personalize}\label{time-to-re-personalize}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-conversations-1} 

}

\caption{Conversations Needed to Re-Personalize}\label{fig:fig-conversations}
\end{figure}

5\% believe a new assistant would \emph{never} fully catch up---an
extreme form of perceived lock-in.

\section{Valuation Results}\label{valuation-results}

\subsection{Survey-to-Model Mapping}\label{survey-to-model-mapping}

\begin{longtable}[t]{llll}
\caption{\label{tab:tab-mapping}Mapping: Survey Variables to Model Notation}\\
\toprule
Survey Q & Variable & Model & Description\\
\midrule
\cellcolor{gray!10}{Q12} & \cellcolor{gray!10}{wta\_memory\_erasure} & \cellcolor{gray!10}{W1} & \cellcolor{gray!10}{WTA to erase ChatGPT memory}\\
Q13 & wtp\_claude\_no\_strings & W2 & WTP for Claude (memory intact)\\
\cellcolor{gray!10}{Q14} & \cellcolor{gray!10}{wtp\_claude\_with\_erasure} & \cellcolor{gray!10}{W4} & \cellcolor{gray!10}{WTP for Claude (memory erased)}\\
Q15 & wtp\_claude\_with\_transfer & W3 & WTP for Claude (memory transferred)\\
\cellcolor{gray!10}{Q13 - Q14} & \cellcolor{gray!10}{demand\_suppression} & \cellcolor{gray!10}{W2 - W4} & \cellcolor{gray!10}{Demand suppression from memory}\\
\addlinespace
Q15 - Q14 & portability\_recovery & W3 - W4 & Demand recovered by portability\\
\cellcolor{gray!10}{1-(Q13-Q15)/(Q13-Q14)} & \cellcolor{gray!10}{phi\_eff} & \cellcolor{gray!10}{phi\_eff} & \cellcolor{gray!10}{Effective portability share}\\
\bottomrule
\end{longtable}

\subsection{WTA for Memory Erasure}\label{wta-for-memory-erasure}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-wta-1} 

}

\caption{WTA for Permanent Memory Erasure}\label{fig:fig-wta}
\end{figure}

\begin{longtable}[t]{lrrrrrr}
\caption{\label{tab:tab-valuation}Valuation Summary Statistics}\\
\toprule
Measure & N & \% at \$0 & Mean & Median & SD & IQR\\
\midrule
\cellcolor{gray!10}{WTA memory erasure (W1)} & \cellcolor{gray!10}{203} & \cellcolor{gray!10}{13.8} & \cellcolor{gray!10}{162.7} & \cellcolor{gray!10}{50} & \cellcolor{gray!10}{284.8} & \cellcolor{gray!10}{95}\\
WTP Claude no strings (W2) & 204 & 55.4 & 4.7 & 0 & 7.3 & 5\\
\cellcolor{gray!10}{WTP Claude with erasure (W4)} & \cellcolor{gray!10}{204} & \cellcolor{gray!10}{66.7} & \cellcolor{gray!10}{3.9} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{8.2} & \cellcolor{gray!10}{5}\\
WTP Claude with transfer (W3) & 204 & 49.0 & 6.1 & 5 & 8.2 & 10\\
\bottomrule
\end{longtable}

\subsection{WTP Across Scenarios}\label{wtp-across-scenarios}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-wtp-1} 

}

\caption{WTP for Claude Pro: Within-Subject Comparison}\label{fig:fig-wtp}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-demand-1} 

}

\caption{Demand Curves and Margin Decomposition}\label{fig:fig-demand}
\end{figure}

The demand curves show the gap between scenarios: the vertical distance
between the ``no strings'' and ``with erasure'' curves represents demand
suppression, while the distance from ``with transfer'' to ``with
erasure'' represents portability recovery.

\subsection{Demand Suppression and
Portability}\label{demand-suppression-and-portability}

\textbf{Demand suppression} (Q13 \(-\) Q14): mean = \$1.21, SD = \$6.7,
\emph{t}-test against zero: \emph{p} = 0.0108.

\textbf{Portability recovery} (Q15 \(-\) Q14): mean = \$2.46, SD =
\$6.85, \emph{t}-test against zero: \emph{p} = 6.91e-07.

\textbf{Effective portability} (\(\hat{\varphi}_{eff}\)): median = 1,
mean = 1.02 (N = 50 with nonzero denominator).

\textbf{Consistency check}: 74.3\% of respondents have W2 \(\geq\) W3
\(\geq\) W4 (theory-consistent ordering); 96\% have W2 \(\geq\) W4.

\begin{longtable}[t]{lrrrr}
\caption{\label{tab:tab-sensitivity}Sensitivity: Censoring Assumptions}\\
\toprule
Scenario & WTA Mean & WTP No Strings & WTP Erasure & WTP Transfer\\
\midrule
\cellcolor{gray!10}{Baseline (excl. censored)} & \cellcolor{gray!10}{162.7} & \cellcolor{gray!10}{4.7} & \cellcolor{gray!10}{3.9} & \cellcolor{gray!10}{6.1}\\
Censor 'No amount' at \$1,000 & 174.9 & 5.4 & 4.6 & 6.8\\
\cellcolor{gray!10}{Censor 'No amount' at \$2,000} & \cellcolor{gray!10}{189.4} & \cellcolor{gray!10}{5.4} & \cellcolor{gray!10}{4.6} & \cellcolor{gray!10}{6.8}\\
\bottomrule
\end{longtable}

\subsection{WTA by Perceived
Improvement}\label{wta-by-perceived-improvement}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-wta-imp-1} 

}

\caption{Mean WTA by Perceived Improvement Level}\label{fig:fig-wta-imp}
\end{figure}

\section{Mechanisms}\label{mechanisms}

\subsection{Demand Suppression and Usage
Intensity}\label{demand-suppression-and-usage-intensity}

If memory and usage are complements (\(u_{tm} > 0\)), heavier users
should exhibit greater demand suppression. We regress (Q13 \(-\) Q14) on
usage frequency, controlling for demographics.

\begin{longtable}[t]{lrrrr}
\caption{\label{tab:tab-reg}OLS: Demand Suppression on Usage Frequency + Demographics}\\
\toprule
Term & Estimate & SE & t & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{3.093} & \cellcolor{gray!10}{2.351} & \cellcolor{gray!10}{1.315} & \cellcolor{gray!10}{0.190}\\
freq\_num & 0.501 & 0.448 & 1.118 & 0.265\\
\cellcolor{gray!10}{age\_group25-34} & \cellcolor{gray!10}{-2.880} & \cellcolor{gray!10}{1.867} & \cellcolor{gray!10}{-1.543} & \cellcolor{gray!10}{0.125}\\
age\_group35-44 & -2.809 & 1.832 & -1.533 & 0.127\\
\cellcolor{gray!10}{age\_group45-54} & \cellcolor{gray!10}{-5.073} & \cellcolor{gray!10}{1.936} & \cellcolor{gray!10}{-2.620} & \cellcolor{gray!10}{0.010}\\
\addlinespace
age\_group55-64 & -2.404 & 2.275 & -1.056 & 0.292\\
\cellcolor{gray!10}{age\_group65+} & \cellcolor{gray!10}{-3.700} & \cellcolor{gray!10}{2.510} & \cellcolor{gray!10}{-1.474} & \cellcolor{gray!10}{0.142}\\
genderNon-binary & -2.470 & 5.304 & -0.466 & 0.642\\
\cellcolor{gray!10}{genderWoman} & \cellcolor{gray!10}{-0.468} & \cellcolor{gray!10}{0.981} & \cellcolor{gray!10}{-0.476} & \cellcolor{gray!10}{0.634}\\
educationDoctoral or professional degree & 2.739 & 4.293 & 0.638 & 0.524\\
\addlinespace
\cellcolor{gray!10}{educationHigh school or less} & \cellcolor{gray!10}{-3.111} & \cellcolor{gray!10}{1.483} & \cellcolor{gray!10}{-2.097} & \cellcolor{gray!10}{0.037}\\
educationMaster's degree & -0.122 & 1.519 & -0.080 & 0.936\\
\cellcolor{gray!10}{educationSome college} & \cellcolor{gray!10}{1.066} & \cellcolor{gray!10}{1.154} & \cellcolor{gray!10}{0.924} & \cellcolor{gray!10}{0.357}\\
\bottomrule
\end{longtable}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-supp-freq-1} 

}

\caption{Demand Suppression by Usage Frequency}\label{fig:fig-supp-freq}
\end{figure}

\subsection{Memory Awareness vs.~Perceived
Improvement}\label{memory-awareness-vs.-perceived-improvement}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-wta-2x2-1} 

}

\caption{WTA by Memory Awareness and Perceived Improvement}\label{fig:fig-wta-2x2}
\end{figure}

This 2\$\times\$2 decomposition tests the ``behavioral wedge'': do
respondents who are \emph{unaware} their AI remembers them but
nonetheless rate memory as valuable exhibit different WTA? If so, WTA
may reflect general aversion to data loss rather than experienced
personalization value.

\subsection{Concentration Beliefs vs.~Actual
Multihoming}\label{concentration-beliefs-vs.-actual-multihoming}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{C:/Users/JimenezR/Documents/GitHub/ai-switching-costs/output/reports/ai_usage_pilot_report_files/figure-latex/fig-conc-1} 

}

\caption{Concentration Beliefs vs. Actual Multihoming}\label{fig:fig-conc}
\end{figure}

\section{Design Calibration}\label{design-calibration}

This section summarizes findings relevant to the full experiment design.

\subsection{BDM Price Range}\label{bdm-price-range}

The WTA distribution for memory erasure (Q12) suggests:

\begin{itemize}
\tightlist
\item
  14\% accept \$0 (no value from memory)
\item
  The 25th--75th percentiles span \$5 to \$100
\item
  1.5\% say ``no amount'' (right-censored)
\end{itemize}

\textbf{Recommendation}: A BDM price list from \$0 to \$100 in \$5
increments would capture the bulk of the distribution while maintaining
incentive compatibility. Consider a broader range (\$0--\$500) for the
WTA question if budget permits.

\subsection{Stratification Candidates}\label{stratification-candidates}

\begin{longtable}[t]{lrrrr}
\caption{\label{tab:stratification}Covariates Predicting WTA (p < 0.10)}\\
\toprule
Term & Estimate & SE & t & p\\
\midrule
\cellcolor{gray!10}{frequency\_ordered.L} & \cellcolor{gray!10}{120.572} & \cellcolor{gray!10}{48.011} & \cellcolor{gray!10}{2.511} & \cellcolor{gray!10}{0.013}\\
ai\_remembersYes & -114.900 & 60.649 & -1.895 & 0.060\\
\cellcolor{gray!10}{perceived\_improvement\_num} & \cellcolor{gray!10}{34.197} & \cellcolor{gray!10}{15.892} & \cellcolor{gray!10}{2.152} & \cellcolor{gray!10}{0.033}\\
\bottomrule
\end{longtable}

\subsection{Preliminary Effect Sizes}\label{preliminary-effect-sizes}

For power calculations:

\begin{itemize}
\tightlist
\item
  \textbf{Demand suppression} (Q13 \(-\) Q14): Cohen's \(d\) = 0.181
\item
  \textbf{Portability recovery} (Q15 \(-\) Q14): Cohen's \(d\) = 0.36
\end{itemize}

These within-subject effect sizes serve as upper bounds for the
between-subjects design. The between-subjects experiment should plan for
effect sizes approximately 50--70\% of these values.

\newpage

\section{Appendix}\label{appendix}

\subsection{Survey Completion Time}\label{survey-completion-time}

\begin{longtable}[t]{rrrrrr}
\caption{\label{tab:duration}Completion Time (minutes)}\\
\toprule
Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max.\\
\midrule
2.2 & 4.2 & 5.2 & 6 & 6.9 & 25.3\\
\bottomrule
\end{longtable}

\subsection{Awareness of Claude Import
Feature}\label{awareness-of-claude-import-feature}

6.8\% were aware of Claude's ChatGPT memory import feature before the
survey. Among those aware (N = 14), 3 had actually used it.

\subsection{Forecast: Quality After
Erasure}\label{forecast-quality-after-erasure}

Mean forecast quality after one month of re-use: 3.9 / 7 (1 =
substantially worse, 7 = substantially better). Respondents expect
moderate degradation but not catastrophic loss.

\subsection{Forecast: Transfer
Fidelity}\label{forecast-transfer-fidelity}

Mean expected transfer fidelity: 56\%. Distribution: 0\%: 20, 100\%: 29,
25\%: 33, 50\%: 56, 75\%: 68.

\end{document}
